language: php

php:
  - 7.0

before_install:
  - composer self-update

before_script:
  - sudo ln -s $TRAVIS_BUILD_DIR /common-php
  - composer install

script:
  - make test-coverage

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --access-token="d4e014d14306737a8392d1ece33117a0418bda50e0749f426c8e8e3ca5e49f9e" --format=php-clover $TRAVIS_BUILD_DIR/coverage.clover